version: 2

project_name: spc

before:
  hooks:
    - make clean
    - go generate ./...
    - go mod tidy
    - ./scripts/generate-changelog.sh {{ .Tag }}
    - ./scripts/generate-release-notes.sh {{ .Tag }}

builds:
  - main: ./main.go
    binary: spc.exe
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    flags:
      - -trimpath
    gcflags:
      - all=-l
    ldflags:
      - -s -w -X github.com/Norgate-AV/spc/internal/version.Version={{.Version}}
      - -X github.com/Norgate-AV/spc/internal/version.Commit={{.Commit}}
      - -X github.com/Norgate-AV/spc/internal/version.Date={{.Date}}
      - -X github.com/Norgate-AV/spc/internal/version.BuiltBy=goreleaser

archives:
  - files:
      - LICENSE*
      - README*
      - CHANGELOG*
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  disable: true

release:
  github:
    owner: Norgate-AV
    name: spc
  draft: false
  mode: replace
  footer: |
    **Full Changelog**: https://github.com/Norgate-AV/spc/compare/{{ .PreviousTag }}...{{ .Tag }}

scoops:
  - name: spc
    repository:
      owner: Norgate-AV
      name: scoop-norgateav-crestron
      token: "{{ .Env.RELEASE_TOKEN }}"
    directory: bucket
    homepage: https://github.com/Norgate-AV/spc
    description: "A better way to compile Crestron SIMPL+ files"
    license: MIT
